name: Docker Matrix Example with execude
on:
  push:

jobs:
  docker-matrix:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        image: [hello-world, alpine]
        exclude:
            - images: alpine
              os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          sudo apt install docker
          echo "Running Docker image: ${{ matrix.image }} on OS: ${{ matrix.os }}"
          docker run ${{ matrix.image }}
