# This is a basic workflow to help you get started with Actions

name: multi job example
env:
  file_name: dragon.txt
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run  script
        run: |
          chmod +x ascii_script.sh
          ./ascii_script.sh
      
      - name : upload artifact
        uses: actions/upload-artifact@v4
        with:
           name : dragon.txt
           path: dragon.txt
  test:
    runs-on: ubuntu-latest
    needs: build   # test will run only if build is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name : download artifact
        uses: actions/download-artifact@v4
        with:
           name : dragon.txt
           pattern: dragon.txt


      - name: verify file dragon.txt
        run: cat $file_name

  deploy:
    runs-on: ubuntu-latest
    needs: test   # deploy will run only if test is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: echo "🚀 Deploying application..."
