name: Manual Trigger with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose deployment environment"
        required: true
        default: "dev"
      version:
        description: "Application version to deploy"
        required: false

jobs:
    test:
     runs-on: ubuntu-latest
     steps:
      - name: check file preset or not
        run: |
          sudo apt install locate
          locate ascii_script.sh
          echo " files is preset"

    deploy:
     needs : test
     runs-on: ubuntu-latest
     steps:
      - name: Show selected inputs
        run: |
          sleep 30s
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          
