
name: Manual Trigger with Inputs + Concurrency

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose deployment environment"
        required: true
        default: "dev"
      version:
        description: "Application version to deploy"
        required: false

#Concurrency makes sure that only one run of a workflow (or job group) runs at a time.
#If a new run starts, the old one can either continue or be cancelled.        
#concurrency:
  #group: deploy-${{ github.event.inputs.environment }}   # group by environment
  #cancel-in-progress: true   # cancel previous run if a new one starts

jobs:
    test:
     runs-on: ubuntu-latest
     steps:
      - name: check file preset or not
        run: |
          echo " deployement files is preset"


    deploy:
     needs : test
     runs-on: ubuntu-latest
     steps:
      - name: Show selected inputs
        run: |
          sleep 600s
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          
